spring.application.name:
  CellDetection
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.eleven.celldetection.entity
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cell_detection?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #?????????filters?stat:????????????sql?????'wall'????????SQL???log4j?????
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#  datasource:
#    #    driver-class-name: com.mysql.cj.jdbc.Driver
#    #    url: jdbc:mysql://localhost:3306/db01?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
#    #    username: root
#    #    password: 123abc123
#
#    driver-class-name: com.kingbase8.Driver
#    url: jdbc:kingbase8://localhost:54321/test?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
#    username: system
#    password: 123abc123

server:
  port: 8080

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

